services:
  api-transacoes:
    build: .
    container_name: desafio-itau-api
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
    # Healthcheck: O Docker verifica se a API est√° viva
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3